In [4]:
import pandas as pd
from database.connection import get_connection
import psycopg2
import os

In [1]:
from etl.extract import (
    load_known_platforms,
    get_video_ids_since_date,
    fetch_video_metadata
)
from config.settings import Settings

In [2]:
known_platforms = load_known_platforms()

all_video_ids = []

for channel_id in Settings.CHANNEL_IDS:
    ids = get_video_ids_since_date(channel_id)
    all_video_ids.extend(ids)

rows = fetch_video_metadata(
    all_video_ids,
    known_platforms
)

Loaded 412 cached platforms from DB
Detected aHg5BZamsSs -> Regular
Detected ijAoGe0fo8I -> Regular
Detected vwBVBrVTHbM -> Short
Detected XX191Zl2VWc -> Regular
Detected p2ZoTwk2CN0 -> Regular
Detected 7gjvdB3eITA -> Regular
Detected ixFhMqkdeXA -> Regular
Detected 0Oca32nLOMQ -> Regular
Detected uKqQQkJwk4E -> Regular
Detected WNXHB1aunEU -> Regular
Fetched 50 videos (quota: 4)
Fetched 50 videos (quota: 5)
Detected -jP80rIp8m8 -> Regular
Detected ryiBkOF2-qQ -> Short
Detected euYqGAdfPZM -> Regular
Detected 80J_YOQFOJ8 -> Regular
Detected 3ynTkkmsSFc -> Short
Fetched 50 videos (quota: 6)
Fetched 50 videos (quota: 7)
Detected SyItlk8r1fk -> Regular
Detected lQgMKU1JZ-Q -> Regular
Detected oWPn_W4bpu8 -> Regular
Detected VX8BRSOeKw4 -> Regular
Detected 38qPgg_MDYI -> Regular
Detected u7J0L4pmPvs -> Regular
Detected 254dMdynpak -> Regular
Detected QexWNrl7su0 -> Regular
Detected o5QFb-WujEU -> Regular
Detected PUDsvxQhENE -> Regular
Detected RabVSZD7LVM -> Regular
Detected j3e1Bvt7WzM -> Regular
Detected NJCpsS_mUWc -> Regular
Detected JGQP6jiY4AQ -> Regular
Detected WgMbk9fE0TM -> Regular
Detected 1NfMD_JRlXw -> Regular
Detected 25YEJLsQ6Tk -> Regular
Detected ujqD1Hb-ruA -> Regular
Detected JB4GRLX9PS4 -> Regular
Detected QtFidZnCLK8 -> Regular
Detected po1cOkAd7mI -> Regular
Fetched 50 videos (quota: 8)
Detected tDhRD96y47I -> Regular
Fetched 50 videos (quota: 9)
Fetched 50 videos (quota: 10)
Fetched 50 videos (quota: 11)
Fetched 49 videos (quota: 12)

In [5]:
df_raw = pd.DataFrame(rows)
display(df_raw)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,aHg5BZamsSs,MMC probing fake MC syndicate amid alleged ins...,The Malaysian Medical Council (MMC) will lead ...,"['news', 'the star tv', 'the star', 'thestartv...",25,The Star,2026-06-20T14:14:41Z,240,6,0,Regular,2026-06-21 00:39:09.499079,PT5M55S
1,ijAoGe0fo8I,One killed and several injured in train collis...,A train driver was killed and dozens more inju...,"['news', 'the star tv', 'the star', 'thestartv...",25,The Star,2026-06-20T14:03:59Z,506,5,3,Regular,2026-06-21 00:39:09.499079,PT1M46S
2,vwBVBrVTHbM,Here are the top 3 #StatePolls2026 stories for...,Stay up to date with our daily 2026 state poll...,"['news', 'the star tv', 'the star']",25,The Star,2026-06-20T13:16:16Z,628,2,0,Short,2026-06-21 00:39:09.499079,PT29S
3,XX191Zl2VWc,PM Anwar backs Nallini to strengthen Media Cou...,Prime Minister Datuk Seri Anwar Ibrahim expres...,"['news', 'the star tv', 'the star', 'thestartv...",25,The Star,2026-06-20T10:39:08Z,515,10,5,Regular,2026-06-21 00:39:09.499079,PT59S
4,p2ZoTwk2CN0,RM1mil allocation for media workers under Tabu...,The government has allocated RM1mil for Tabung...,"['news', 'the star tv', 'the star', 'thestartv...",25,The Star,2026-06-20T10:16:08Z,199,1,0,Regular,2026-06-21 00:39:09.499079,PT3M6S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,wXu4eP-H3Z0,4 Sekeluarga Maut: Proses Bedah Siasat Dijalan...,"Buletin Pagi siaran Isnin, 15 Jun 2026 bersama...",[],25,Buletin TV3,2026-06-15T02:02:13Z,24709,172,5,Regular,2026-06-21 00:39:09.499079,PT28M38S
445,xj3GMetPBjo,NAHAS UDARA | 12 Maut Pesawat Penerjun Udara T...,Sekurang-kurangnya 12 maut apabila sebuah pesa...,"['BU', 'Buletin TV3', 'buletin utama', 'buleti...",25,Buletin TV3,2026-06-15T01:55:44Z,9762,77,2,Regular,2026-06-21 00:39:09.499079,PT47S
446,W3fR4UiEc4Y,"ISU ROHINGYA | Ada Mohon Jadi AJK Kampung, Lak...",Kewujudan komuniti Rohingya di beberapa kawasa...,"['BU', 'Buletin TV3', 'buletin utama', 'buleti...",25,Buletin TV3,2026-06-15T01:52:40Z,6276,77,103,Regular,2026-06-21 00:39:09.499079,PT1M26S
447,632XYD6l4n0,PERANG ASIA BARAT | AS-Iran Capai Perjanjian D...,Amerika Syarikat dan Iran mencapai persetujuan...,"['BU', 'Buletin TV3', 'buletin utama', 'buleti...",25,Buletin TV3,2026-06-15T01:51:10Z,1701,22,12,Regular,2026-06-21 00:39:09.499079,PT1M35S
448,EQQH-C6vPS8,EMPAT SEKELUARGA MAUT | Proses Bedah Siasat Di...,Untuk perkembangan proses bedah siasat jenazah...,"['BU', 'Buletin TV3', 'buletin utama', 'buleti...",25,Buletin TV3,2026-06-15T01:50:23Z,7845,52,25,Regular,2026-06-21 00:39:09.499079,PT3M6S

In [3]:
from psycopg2.extras import execute_values
from database.connection import get_connection

In [7]:
conn = get_connection()
cur = conn.cursor()

In [11]:
from psycopg2.extras import execute_values

In [12]:
query = """
    INSERT INTO public.video_metrics_time_series (
        video_id,
        title,
        description,
        tags,
        category_id,
        channel_title,
        published_at,
        views,
        likes,
        comments_count,
        platform,
        fetched_at,
        duration
    ) VALUES %s
"""

execute_values(cur, query, rows, page_size=5000)

In [35]:
conn.rollback()

In [36]:
cur.execute(
    """
    ALTER TABLE public.video_metrics_time_series
        DROP COLUMN IF EXISTS fetched_at_sgt,
        DROP COLUMN IF EXISTS published_at_sgt
    """
)

In [13]:
df = pd.read_sql(
    "SELECT * FROM video_metrics_time_series",
    conn
)

C:\Users\User\AppData\Local\Temp\ipykernel_27060\4205903146.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

In [14]:
display(df)

,id,video_id,title,description,tags,category_id,channel_title,published_at,views,likes,comments_count,platform,fetched_at,duration
0,2576,aHg5BZamsSs,MMC probing fake MC syndicate amid alleged ins...,The Malaysian Medical Council (MMC) will lead ...,"['news', 'the star tv', 'the star', 'thestartv...",25,The Star,2026-06-20 14:14:41,240,6,0,Regular,2026-06-21 00:39:09,PT5M55S
1,2577,ijAoGe0fo8I,One killed and several injured in train collis...,A train driver was killed and dozens more inju...,"['news', 'the star tv', 'the star', 'thestartv...",25,The Star,2026-06-20 14:03:59,506,5,3,Regular,2026-06-21 00:39:09,PT1M46S
2,2578,vwBVBrVTHbM,Here are the top 3 #StatePolls2026 stories for...,Stay up to date with our daily 2026 state poll...,"['news', 'the star tv', 'the star']",25,The Star,2026-06-20 13:16:16,628,2,0,Short,2026-06-21 00:39:09,PT29S
3,2579,XX191Zl2VWc,PM Anwar backs Nallini to strengthen Media Cou...,Prime Minister Datuk Seri Anwar Ibrahim expres...,"['news', 'the star tv', 'the star', 'thestartv...",25,The Star,2026-06-20 10:39:08,515,10,5,Regular,2026-06-21 00:39:09,PT59S
4,2580,p2ZoTwk2CN0,RM1mil allocation for media workers under Tabu...,The government has allocated RM1mil for Tabung...,"['news', 'the star tv', 'the star', 'thestartv...",25,The Star,2026-06-20 10:16:08,199,1,0,Regular,2026-06-21 00:39:09,PT3M6S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1672,1224,v76wvD1vvhQ,Top STPM students to get public university sch...,The country’s top Sijil Tinggi Persekolahan Ma...,"['news', 'the star tv', 'the star', 'thestartv...",25,The Star,2026-06-18 10:26:21,638,8,3,Regular,2026-06-20 04:21:14,PT4M35S
1673,1225,uqA35LurToM,PERJANJIAN AS-IRAN | Majoriti Saham Asia Melon...,Perkembangan terbaharu konflik Asia Barat memb...,"['BU', 'Buletin TV3', 'buletin utama', 'buleti...",25,Buletin TV3,2026-06-18 12:17:25,966,15,2,Regular,2026-06-20 04:21:14,PT1M34S
1674,1226,OGSa1qJX6Yw,"PERANG ASIA BARAT | Netanyahu Tetap Berdegil, ...","Pemimpin rejim, Benjamin Netanyahu tetap berde...","['BU', 'Buletin TV3', 'buletin utama', 'buleti...",25,Buletin TV3,2026-06-16 02:09:17,5333,38,42,Regular,2026-06-20 04:21:14,PT54S
1675,1227,xXx9Do6zGAM,MAHKAMAH | Wanita Didakwa Bunuh Warga Indonesi...,Seorang suri rumah berdepan tuduhan membunuh s...,"['BU', 'Buletin TV3', 'buletin utama', 'buleti...",25,Buletin TV3,2026-06-19 12:34:19,887,13,1,Regular,2026-06-20 04:21:14,PT51S
1676,1228,NcfWTboDjWY,[LIVE] Gurun blast: Latest updates from Sultan...,[LIVE] Gurun blast: Latest updates from Sultan...,"['nstonline', 'NST', 'New Straits Times', 'news']",25,NST Online,2026-06-18 13:03:53,273,2,0,Regular,2026-06-20 04:21:14,PT21S

In [17]:
cursor.execute(
    """
    UPDATE public.video_metrics_time_series
    SET
        published_at_sgt = published_at AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Singapore',
        fetched_at_sgt = fetched_at AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Singapore';
    """
)

In [15]:
cur.close()
conn.close()

In [2]:
import logic
print(logic)
print(logic.__file__)

dir(logic)

import os

print(os.listdir(next(iter(logic.__path__))))

print(logic.__path__)

<module 'logic' from 'C:\\Users\\User\\Desktop\\YT_TimeSeries\\logic\\__init__.py'>
C:\Users\User\Desktop\YT_TimeSeries\logic\__init__.py
['time_series_collection_optimized.py', 'time_series_collection_supabase.py', '__init__.py', '__pycache__']
['C:\\Users\\User\\Desktop\\YT_TimeSeries\\logic']

In [1]:
from etl.extract import load_known_platforms

platforms = load_known_platforms()

print(platforms)

Loaded 412 cached platforms from DB
{'_i_jedqiZ98': 'Regular', '_Jq93RTajzg': 'Short', '_QfdSSgGPDA': 'Short', '_t1Z2pqkpYI': 'Regular', '_TSfJNZsB-g': 'Regular', '-_EkEWVzWQ8': 'Regular', '-8pErDoPRyU': 'Regular', '-ahlkfVPvDM': 'Regular', '-bSJgXzCfh0': 'Regular', '-jfjUAmu1OM': 'Short', '-lJ2aF-5sEQ': 'Regular', '-M-ZcELjWpA': 'Regular', '-n7VVl_20jI': 'Short', '-QVcHkJqyiE': 'Short', '-QyrOsS47YQ': 'Short', '0bjlGR8UXwg': 'Regular', '0gKlsk_32NQ': 'Regular', '0HLIff4xuMA': 'Regular', '0PH2QSfGJ3I': 'Regular', '0SjkNn9LMp4': 'Regular', '0y-0y9iquak': 'Regular', '0Yi5nlzdrW4': 'Regular', '1dTCJLSaTr4': 'Regular', '1JrSN370q-8': 'Regular', '1Kr4LAMm2og': 'Regular', '2BSEuRPU6e0': 'Short', '2d1MowONYmU': 'Regular', '2F9zv8YXrDw': 'Short', '2zS-jCQ6Ap0': 'Short', '3-PNtLSJRGs': 'Regular', '3c2-5fPlDD4': 'Short', '3CRA2mJPY7E': 'Regular', '3cT0FNmiXjo': 'Regular', '3fT26kAI3A0': 'Regular', '3gyNtKI5MZg': 'Regular', '3KTpdJB6LWA': 'Regular', '3PEbq17t1-U': 'Regular', '3QIRrK6xNhk': 'Regular', '3QVR_aDTXOo': 'Short', '3TpARPSBrRk': 'Regular', '41utKVj00JU': 'Regular', '47SvW0wTz6I': 'Regular', '4A_JIvBog68': 'Regular', '4b-l5GtD_yU': 'Short', '4EKNbKfQfvE': 'Regular', '4fF2RyJ8adg': 'Regular', '4j6elsqsdqg': 'Regular', '4LDRj7X2a3k': 'Short', '4mFarIXbJUM': 'Regular', '4S0d2OWH-I0': 'Regular', '4tkKykzEDhY': 'Regular', '4TmsvcQMo_k': 'Regular', '4Ukq1j6oAVQ': 'Regular', '4wYGDY7EWFk': 'Short', '50Fu2jbNNH0': 'Short', '52GW7KmbotA': 'Regular', '57kG1OX3Itc': 'Regular', '5ovH0LLZyPk': 'Short', '5TO70wXIHOQ': 'Regular', '5zvyBkIkuT8': 'Regular', '632XYD6l4n0': 'Regular', '6kkVf754ZB4': 'Regular', '6Ri8tuhmb4M': 'Short', '6RT6NptM4Yc': 'Regular', '6z5gWYTJFRU': 'Regular', '7CWlg1KNQ_U': 'Regular', '7eobJI3FgWQ': 'Short', '7il9TkkLlgU': 'Short', '7lhVSZeGhlc': 'Regular', '7sy-zkFepXk': 'Short', '88DKhbus_RE': 'Short', '8d5YhePtMFU': 'Regular', '8HTSoQEn38E': 'Regular', '8hY1_NQ9SP0': 'Regular', '8OPOeGUbzBg': 'Regular', '8PhzeZ7bKvM': 'Regular', '8q09wnB_e3I': 'Regular', '8zKxuFTqeng': 'Short', '92MWIgCQJ64': 'Regular', '95Xzv9Nw2bU': 'Regular', '9FoFJIrwLNw': 'Regular', '9KgzhFbYhNk': 'Regular', '9SFx8NB4BKA': 'Short', 'A8Os3rGMTpg': 'Regular', 'ACk_t0ysIBY': 'Regular', 'aFQ08-_WDCc': 'Regular', 'AodER6lm0io': 'Short', 'aOsKAFzeaNU': 'Regular', 'ASWay_5H6u4': 'Regular', 'AtN9MnfkRGg': 'Regular', 'aZxGzpaEt3U': 'Short', 'b-lRhmh9ld4': 'Short', 'B4DUeB1uKkw': 'Regular', 'bAqgSB3ywhU': 'Short', 'BDiKeW9ATwA': 'Regular', 'BDYO-dNMlXw': 'Regular', 'bFdXq_jYxAc': 'Regular', 'BhsvlQ1VR4A': 'Short', 'bIjGqjuqLKc': 'Short', 'biyrGI9NLU4': 'Regular', 'bmqLVITmCeE': 'Regular', 'bNlN_myUZJM': 'Regular', 'bOfS_dnWxC8': 'Regular', 'bviluDW4UmE': 'Regular', 'BwojgPdal60': 'Short', 'bXsY9QFcFB0': 'Short', 'c_nvOMtFx8M': 'Regular', 'C9qfC644Ris': 'Regular', 'CEeXyZn0hg0': 'Regular', 'cfghg8AeYec': 'Short', 'cJoxcVJ6Ut8': 'Short', 'cjYq6JmBsAw': 'Short', 'cO2ameOiEVw': 'Short', 'COchX7ZhnHU': 'Short', 'cQKmGxO9kns': 'Regular', 'd-z23JU3A00': 'Regular', 'd1BYSjRpDb4': 'Regular', 'dFjnrm0A1rM': 'Short', 'Dhjose-XGp0': 'Regular', 'DjDsMpeR8jo': 'Regular', 'DP5L91PPzbg': 'Short', 'DVA2KmGiXrg': 'Regular', 'dVHBYhtOIN8': 'Short', 'dWSgxNo8Vdw': 'Regular', 'DzB_T4g-D_Y': 'Short', 'DZmks6jUGDg': 'Regular', 'DzSpdBv_yoM': 'Regular', 'e5cbdsCnnnU': 'Short', 'E5LBdU0IWxI': 'Regular', 'e6nEErIPsS0': 'Short', 'EcFuItwotmU': 'Short', 'eDk3Lw1h6EA': 'Short', 'EdkukjlpoJU': 'Short', 'EDM2HmfACKk': 'Regular', 'eEMjMNC0xE0': 'Regular', 'EjhoGoHpqG8': 'Regular', 'EQQH-C6vPS8': 'Regular', 'EwnLpdAQ59E': 'Regular', 'EwqyocLLMrQ': 'Short', 'F1zNVsOAupY': 'Regular', 'F2mVk7gcaUk': 'Regular', 'F8PDzhcMGH8': 'Short', 'faqYaATJjok': 'Regular', 'fbiUqNIrQEQ': 'Regular', 'fD1jfER8COs': 'Regular', 'FGsWgzZ50dE': 'Regular', 'fJF8q3xXfpw': 'Regular', 'FM-KberdLTU': 'Regular', 'foNl_kuI8pA': 'Short', 'fpy2EB5idGw': 'Regular', 'frO8NMyaoR8': 'Short', 'FUj53xfbAQ4': 'Regular', 'fVyPLSzfSPM': 'Regular', 'fwIcaGQYmdk': 'Regular', 'FZgJ-W_I0ZM': 'Regular', 'gcS_V2cLeaA': 'Short', 'gHBERZQcEMY': 'Short', 'GKcRFAwnnpE': 'Regular', 'GorUdkYterM': 'Regular', 'graGPI-QPCA': 'Regular', 'gxIUWBIS26A': 'Regular', 'GYiz57BmbVk': 'Regular', 'h_AqKDA5S6U': 'Regular', 'h3RXQYabffQ': 'Regular', 'hACtBIrnz7g': 'Short', 'hjY4RHTTEfY': 'Regular', 'HzixCDsB6-E': 'Short', 'i_w07U0QY_g': 'Regular', 'i0KhlXwUnAo': 'Regular', 'i64CjhxC6G8': 'Regular', 'i6dumf5XevA': 'Regular', 'i7acUt8L_CE': 'Regular', 'i8mMPTxiLAQ': 'Regular', 'i9x9nDOgiLU': 'Regular', 'ib_bmoH6sE4': 'Regular', 'ibLFoASePqc': 'Short', 'iD0MVkm0mmg': 'Regular', 'IEabkS1ezDE': 'Regular', 'ifL4X_1An10': 'Regular', 'II3iZ-q64F0': 'Regular', 'iKudZ5vZnVw': 'Regular', 'iprMJJAKgPI': 'Short', 'IuETd4xprXg': 'Regular', 'IwkhHCulp3c': 'Regular', 'iXSjR6iyyNQ': 'Regular', 'iZ8VYROELHU': 'Short', 'J2DugHVUD0w': 'Short', 'j7Es77mFkSw': 'Short', 'jbbxopyp9ck': 'Short', 'jhYKaSwYrP8': 'Regular', 'jJPHiZIY-24': 'Regular', 'JKgK-eMaysU': 'Regular', 'jkX0vEWsRaA': 'Regular', 'JLE2Z08BzNk': 'Regular', 'jLNyRS648pc': 'Regular', 'jpAD8ZV8X90': 'Regular', 'jUDbl1Ue_0M': 'Regular', 'JZ0y1Mrnh5E': 'Regular', 'kgx1w5AtWpA': 'Regular', 'KHo_o3E1TMY': 'Regular', 'KJ4A43KAK0w': 'Regular', 'kmWFkxy0vFI': 'Regular', 'kqKWKEu8t_A': 'Short', 'KrCpsgFyPYA': 'Short', 'krqKemvnTRc': 'Regular', 'kVFiOaLyHwE': 'Regular', 'ky0mfJcFdS8': 'Short', 'L_f6UZ56D7k': 'Regular', 'l0X7Nhl0irs': 'Regular', 'L2rFOVnfuo0': 'Short', 'L8GI2J2gvLk': 'Regular', 'L8xYGbLcmKg': 'Short', 'LaaXO6MsZmo': 'Regular', 'LduXUmHOGcE': 'Short', 'LJwl9oZ90t8': 'Regular', 'Lr_QqG9d5kI': 'Regular', 'lsq0vvWRmlo': 'Regular', 'lTPfCEI_PN8': 'Short', 'Lu1xuq3yvDU': 'Regular', 'lvXdm5w5KZU': 'Regular', 'LYEUQK2AxHE': 'Short', 'm4L3Sc7Ikdk': 'Regular', 'm64HK6N_300': 'Short', 'm7O8E2Y1Nx0': 'Short', 'm9XvqtCfdqM': 'Regular', 'mfgXbYcPxzg': 'Regular', 'mgVnMZ03DaE': 'Regular', 'mJqMRM66_m8': 'Short', 'mjrTMeV9cCw': 'Regular', 'Mobw2jN2V2A': 'Short', 'mom1SArXBiQ': 'Regular', 'MtJA3gJVDnE': 'Short', 'mX4YhzWPg_A': 'Short', 'N92oWbUHmDQ': 'Regular', 'NbgUUFEzw_A': 'Short', 'NcfWTboDjWY': 'Regular', 'nDSnoptNXHc': 'Short', 'nN0eDnDhQaA': 'Regular', 'nnp7PTs7w4w': 'Short', 'nra8gdUHmVU': 'Regular', 'NwRbu114_U0': 'Regular', 'nxoo8qLdYe8': 'Regular', 'NzH1QzvGW3A': 'Regular', 'O5xI2ENbtt4': 'Regular', 'o8QPevvYAW8': 'Regular', 'O9dwcVq_nf0': 'Regular', 'O9S-lgncsfE': 'Regular', 'OemdPTMYnvM': 'Short', 'OGSa1qJX6Yw': 'Regular', 'omTy3L8zT8E': 'Regular', 'ONVd26pKq60': 'Regular', 'OQVAkZHk-AE': 'Regular', 'oSSghBj707I': 'Regular', 'OvinlFvCPVs': 'Regular', 'oxC52dLAfpU': 'Regular', 'OZC6F4sXFHw': 'Short', 'OzGLhHYgB-E': 'Regular', 'OZqPaTH-hkc': 'Regular', 'p0-1s_2zAW0': 'Regular', 'PemoHnDGOFU': 'Regular', 'pgQZGx7Gd9o': 'Short', 'POawg1PTGhk': 'Regular', 'PpJK827GzeI': 'Regular', 'Pqrxlr48tbI': 'Regular', 'psWY8ZnNHGY': 'Regular', 'PT8ww-P8Cls': 'Regular', 'pUP95MbSZfc': 'Regular', 'Pxq4cIU0Hz4': 'Regular', 'PXvtQn2Z_K8': 'Regular', 'PY5HP09T7_g': 'Regular', 'pydfkd0DtbM': 'Regular', 'Q3Xar84ltbs': 'Regular', 'q9ZCmnL305E': 'Regular', 'qAqD8a_Hv3Q': 'Regular', 'Qec7zUsUlWw': 'Regular', 'QEJl4XoACIM': 'Regular', 'qGhX2jurnxk': 'Short', 'Qj-qV55h5YE': 'Regular', 'qJlpzIR-22A': 'Short', 'qLWl7HgdAn0': 'Short', 'QNQd6kTcWk0': 'Short', 'qsbH4t1EBlw': 'Regular', 'qU9raduIkCQ': 'Regular', 'qXSk76xnyFA': 'Regular', 'qZ-xCoSuAoc': 'Regular', 'qZLySwCUjQk': 'Short', 'qZSbBzkmcps': 'Regular', 'qZydptTGyGU': 'Regular', 'QzZYMqFUifo': 'Regular', 'r4YkRsulwZE': 'Regular', 'r7Cyon1CUL8': 'Regular', 'rL_gcPy45nA': 'Regular', 'RTaQKXYtV8I': 'Short', 's9N4Kck2IB0': 'Regular', 'Sbjen741jLA': 'Short', 'SBxckQg3aTM': 'Regular', 'sFEeZx4CUO8': 'Short', 'Sj8foLzXoSg': 'Regular', 'SJjje0R9kOE': 'Short', 'SJUay8nLqLY': 'Short', 'snEiB0iDbKI': 'Regular', 'spnlYN1SszE': 'Short', 'SpZHIp6XOxU': 'Regular', 'sqFxO0pVXu8': 'Regular', 'SraNGcK5lxE': 'Regular', 'stCfeKqap2E': 'Regular', 'sVY_A8XTZO4': 'Regular', 'SWRKVRkN7b0': 'Regular', 'Sy5uc7C8aK0': 'Regular', 'T1YU7Tsm-GI': 'Regular', 'T8EY44cDuhc': 'Short', 'ta3g4WM0H3k': 'Regular', 'tAb21SQ38Qs': 'Regular', 'TH7E6rEn5sI': 'Regular', 'THERQNZl5oo': 'Short', 'TKOUVASdyt0': 'Short', 'TLLJ7eT8pZI': 'Regular', 'TLOjMT-c638': 'Regular', 'tQ3JkNtN7wA': 'Regular', 'tRK7npedfC4': 'Regular', 'tTyWauALdsc': 'Regular', 'tW24vM2U1dU': 'Regular', 'U5kjmmJd-ZA': 'Short', 'Ub0refF4pVM': 'Regular', 'UDZEFlelqpU': 'Regular', 'uH_udtbO9x4': 'Regular', 'ujvOsJbrvMg': 'Regular', 'uk690pkLtJE': 'Regular', 'uOyXcP9TU0Q': 'Regular', 'uqA35LurToM': 'Regular', 'uRRiSPMadf0': 'Short', 'USv9lZDJoHM': 'Regular', 'uVfo_kvTO5w': 'Short', 'UwgpR4nvD2Q': 'Short', 'v76wvD1vvhQ': 'Regular', 'Vh1xuvRkM-4': 'Regular', 'VIi-CjzKAnQ': 'Regular', 'vMGDiY_LbIY': 'Short', 'VOovzq5jQlI': 'Regular', 'VPVMaUwspMU': 'Short', 'vWhv9UCnZVA': 'Regular', 'W3fR4UiEc4Y': 'Regular', 'w3Qn20cZ3eg': 'Regular', 'W5w3vwdBQmw': 'Regular', 'w94HQRHrMNs': 'Regular', 'WAlMq2-PJz8': 'Short', 'Wcn-28ttf0E': 'Regular', 'WEB2wFJ02-8': 'Short', 'wqLEkvuOMNw': 'Short', 'WRJWLAJDLmA': 'Regular', 'WS4PjfLz1LI': 'Regular', 'WT1FGkwGrhc': 'Short', 'wVpCy08NbRU': 'Short', 'wVZR2okMiSw': 'Regular', 'wWLesd-fF8g': 'Short', 'Wx-Dji8YOQI': 'Short', 'Wx8LLGb77V4': 'Short', 'wXu4eP-H3Z0': 'Regular', 'WZjTawctdHw': 'Regular', 'WZZLel8Ec94': 'Regular', 'x10wos-Gb4E': 'Regular', 'X4ydZEePHCs': 'Regular', 'X5HP6jkOvSE': 'Short', 'XgiR78L8ZZw': 'Short', 'XGv6WUSz2hM': 'Short', 'XgXcHH_-544': 'Short', 'xiIWzJWyevc': 'Short', 'xj3GMetPBjo': 'Regular', 'xo0zHI9Wzhw': 'Regular', 'Xqy3fq8KyhU': 'Regular', 'XRS06B58LxA': 'Short', 'xRWAKbjLqfM': 'Regular', 'xXx9Do6zGAM': 'Regular', 'xzDbrYaxXoM': 'Regular', 'y_EwEzhr1J4': 'Short', 'y6QBZzaWWvU': 'Regular', 'Y9ytkxuomWQ': 'Short', 'YA7010ryf1M': 'Short', 'Yb6yFZcmGUU': 'Regular', 'Ybo3KIbB9kg': 'Regular', 'ybYcud7KAQk': 'Regular', 'YCkoLXtp2PM': 'Short', 'yeeYDI3tW2A': 'Regular', 'yEKJE3qHO38': 'Short', 'YinNL9pYmKo': 'Regular', 'yM-djfFaTZA': 'Regular', 'Ynum7vltwkE': 'Short', 'YpUO77P21gc': 'Regular', 'YvrVwBj6BSc': 'Short', 'YwD2dzQT0cc': 'Regular', 'YwJfYLhokyw': 'Short', 'yX0OfeCbJM0': 'Short', 'yxKxPMTiwKw': 'Regular', 'yyrmFpw5YhM': 'Short', 'z3otRH_NvZQ': 'Regular', 'z6JItgyh_Ek': 'Regular', 'Z7lqw3zUtLs': 'Regular', 'zBx-v-16xh8': 'Short', 'ZcFx6VamvNI': 'Regular', 'zDtYdZ0uBFQ': 'Regular', 'zfSwkMzXyQQ': 'Short', 'ZIDxMvLyyhM': 'Regular', 'zIevaps6DHQ': 'Regular', 'zIEVEtDGfr4': 'Short', 'Zivqyqurnao': 'Short', 'zNH7EK3pWtU': 'Short', 'zoXKNxfwJto': 'Regular', 'ZpgyrcS28V4': 'Regular', 'zQK9__d9FGI': 'Short', 'zRiEi00K6XI': 'Regular', 'ZVmOQTj8Vfg': 'Regular', 'ZYUxeVpLRGw': 'Short'}